"""add motivo_error to asistencia

Revision ID: 904378a0e8b4
Revises: d387b37e9436
Create Date: 2025-11-02 10:33:40.311059

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '904378a0e8b4'
down_revision: Union[str, Sequence[str], None] = 'd387b37e9436'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('idx_hp_log_cliente'), table_name='huella_purgada_log')
    op.drop_index(op.f('idx_hp_log_fecha'), table_name='huella_purgada_log')
    op.drop_index(op.f('idx_hp_log_ultfin'), table_name='huella_purgada_log')
    op.drop_table('huella_purgada_log')
    op.add_column('asistencia', sa.Column('motivo_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('asistencia', 'motivo_error')
    op.create_table('huella_purgada_log',
    sa.Column('id', mysql.BIGINT(unsigned=True), autoincrement=True, nullable=False),
    sa.Column('cliente_id', mysql.BIGINT(), autoincrement=False, nullable=False),
    sa.Column('venta_membresia_id', mysql.BIGINT(), autoincrement=False, nullable=True),
    sa.Column('fecha_purgado', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.Column('fecha_fin_ultima_membresia', sa.DATE(), nullable=False),
    sa.Column('id_huella_prev', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('tenia_template', mysql.TINYINT(display_width=1), autoincrement=False, nullable=False),
    sa.Column('nombre', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('apellido', mysql.VARCHAR(length=200), nullable=True),
    sa.Column('documento', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('correo', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('motivo', mysql.ENUM('VENCIDO_3_MESES'), server_default=sa.text("'VENCIDO_3_MESES'"), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb3',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('idx_hp_log_ultfin'), 'huella_purgada_log', ['fecha_fin_ultima_membresia'], unique=False)
    op.create_index(op.f('idx_hp_log_fecha'), 'huella_purgada_log', ['fecha_purgado'], unique=False)
    op.create_index(op.f('idx_hp_log_cliente'), 'huella_purgada_log', ['cliente_id'], unique=False)
    # ### end Alembic commands ###
