"""init mysql

Revision ID: 98a892b80664
Revises: 
Create Date: 2025-09-01 16:22:07.758864

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a892b80664'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_membresia', sa.String(length=120), nullable=False),
    sa.Column('duracion_dias', sa.Integer(), nullable=False),
    sa.Column('cantidad_sesiones', sa.Integer(), nullable=True),
    sa.Column('precio_base', sa.Float(), nullable=False),
    sa.Column('max_accesos_diarios', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_membresia_id'), 'membresia', ['id'], unique=False)
    op.create_table('rol',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_rol', sa.String(length=120), nullable=True),
    sa.Column('descripcion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rol_id'), 'rol', ['id'], unique=False)
    op.create_table('sede',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre_sede', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('telefono', sa.String(length=12), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sede_id'), 'sede', ['id'], unique=False)
    op.create_table('tipo_descuento',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_descuento', sa.String(length=120), nullable=False),
    sa.Column('porcentaje_descuento', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tipo_descuento_id'), 'tipo_descuento', ['id'], unique=False)
    op.create_table('cliente',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=120), nullable=False),
    sa.Column('apellido', sa.String(length=120), nullable=False),
    sa.Column('documento', sa.String(length=20), nullable=False),
    sa.Column('id_huella', sa.Integer(), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=False),
    sa.Column('telefono', sa.String(length=120), nullable=True),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('direccion', sa.String(length=120), nullable=True),
    sa.Column('id_tipo_descuento', sa.Integer(), nullable=True),
    sa.Column('huella_template', sa.LargeBinary(), nullable=True),
    sa.Column('fotografia', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['id_tipo_descuento'], ['tipo_descuento.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('documento')
    )
    op.create_index(op.f('ix_cliente_id'), 'cliente', ['id'], unique=False)
    op.create_index(op.f('ix_cliente_id_huella'), 'cliente', ['id_huella'], unique=True)
    op.create_table('factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('numero_factura', sa.String(length=120), nullable=False),
    sa.Column('fecha_emision', sa.DateTime(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('subtotal', sa.Float(), nullable=True),
    sa.Column('descuento_total', sa.Float(), nullable=True),
    sa.Column('total', sa.Float(), nullable=True),
    sa.Column('metodo_pago', sa.String(length=120), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_factura_id'), 'factura', ['id'], unique=False)
    op.create_table('reporte_asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_sede', sa.Integer(), nullable=True),
    sa.Column('fecha_generacion', sa.DateTime(), nullable=True),
    sa.Column('tipo_reporte', sa.String(length=120), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=True),
    sa.Column('enviado', sa.Boolean(), nullable=True),
    sa.Column('fecha_envio', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_sede'], ['sede.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reporte_asistencia_id'), 'reporte_asistencia', ['id'], unique=False)
    op.create_table('usuario',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre_usuario', sa.String(length=120), nullable=False),
    sa.Column('contraseña_hash', sa.String(length=120), nullable=False),
    sa.Column('correo', sa.String(length=120), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=True),
    sa.Column('id_rol', sa.Integer(), nullable=True),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_rol'], ['rol.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo')
    )
    op.create_index(op.f('ix_usuario_id'), 'usuario', ['id'], unique=False)
    op.create_index(op.f('ix_usuario_nombre_usuario'), 'usuario', ['nombre_usuario'], unique=True)
    op.create_table('venta_membresia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_membresia', sa.Integer(), nullable=True),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('precio_final', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=120), nullable=True),
    sa.Column('sesiones_restantes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_membresia'], ['membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_venta_membresia_id'), 'venta_membresia', ['id'], unique=False)
    op.create_table('asistencia',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_cliente', sa.Integer(), nullable=True),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('id_sede', sa.Integer(), nullable=True),
    sa.Column('fecha_hora_entrada', sa.DateTime(), nullable=True),
    sa.Column('tipo_acceso', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['id_cliente'], ['cliente.id'], ),
    sa.ForeignKeyConstraint(['id_sede'], ['sede.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_asistencia_id'), 'asistencia', ['id'], unique=False)
    op.create_table('detalle_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('descuento_aplicado', sa.Float(), nullable=True),
    sa.Column('total_linea', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_factura_id'), 'detalle_factura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_factura_id'), table_name='detalle_factura')
    op.drop_table('detalle_factura')
    op.drop_index(op.f('ix_asistencia_id'), table_name='asistencia')
    op.drop_table('asistencia')
    op.drop_index(op.f('ix_venta_membresia_id'), table_name='venta_membresia')
    op.drop_table('venta_membresia')
    op.drop_index(op.f('ix_usuario_nombre_usuario'), table_name='usuario')
    op.drop_index(op.f('ix_usuario_id'), table_name='usuario')
    op.drop_table('usuario')
    op.drop_index(op.f('ix_reporte_asistencia_id'), table_name='reporte_asistencia')
    op.drop_table('reporte_asistencia')
    op.drop_index(op.f('ix_factura_id'), table_name='factura')
    op.drop_table('factura')
    op.drop_index(op.f('ix_cliente_id_huella'), table_name='cliente')
    op.drop_index(op.f('ix_cliente_id'), table_name='cliente')
    op.drop_table('cliente')
    op.drop_index(op.f('ix_tipo_descuento_id'), table_name='tipo_descuento')
    op.drop_table('tipo_descuento')
    op.drop_index(op.f('ix_sede_id'), table_name='sede')
    op.drop_table('sede')
    op.drop_index(op.f('ix_rol_id'), table_name='rol')
    op.drop_table('rol')
    op.drop_index(op.f('ix_membresia_id'), table_name='membresia')
    op.drop_table('membresia')
    # ### end Alembic commands ###
