"""add_observaciones_to_cliente

Revision ID: 99dd97e8c086
Revises: c7f4342b966b
Create Date: 2026-01-06 15:28:29.591359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '99dd97e8c086'
down_revision: Union[str, Sequence[str], None] = 'c7f4342b966b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('cliente', sa.Column('observaciones', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cliente', 'observaciones')
    # ### end Alembic commands ###
