"""relax_correo_constraint

Revision ID: c7f4342b966b
Revises: 904378a0e8b4
Create Date: 2026-01-06 15:22:00.166892

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c7f4342b966b'
down_revision: Union[str, Sequence[str], None] = '904378a0e8b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'correo',
               existing_type=mysql.VARCHAR(collation='latin1_bin', length=120),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('cliente', 'correo',
               existing_type=mysql.VARCHAR(collation='latin1_bin', length=120),
               nullable=False)
    # ### end Alembic commands ###
