"""init mysql

Revision ID: f029e7f79f0e
Revises: 
Create Date: 2025-08-28 11:51:03.612127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f029e7f79f0e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('detalle_factura',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_factura', sa.Integer(), nullable=True),
    sa.Column('id_venta', sa.Integer(), nullable=True),
    sa.Column('descripcion', sa.String(length=120), nullable=True),
    sa.Column('cantidad', sa.Integer(), nullable=True),
    sa.Column('precio_unitario', sa.Float(), nullable=True),
    sa.Column('descuento_aplicado', sa.Float(), nullable=True),
    sa.Column('total_linea', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['id_factura'], ['factura.id'], ),
    sa.ForeignKeyConstraint(['id_venta'], ['venta_membresia.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_detalle_factura_id'), 'detalle_factura', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_detalle_factura_id'), table_name='detalle_factura')
    op.drop_table('detalle_factura')
    # ### end Alembic commands ###
